title: <p align="center"> Vijay Karma </p>
logo: /assets/img/VijayKarma.jpg
description: 9+ years of IT experience as Data Engineer, Developing, Implementation of software applications which includes 7 years of experience in Big Data using Spark, Scala, Python, Java, Hadoop, Hive, Snowflake, Apache Airflow and AWS
show_downloads: true
theme: jekyll-theme-minimal

